# Generated by Django 6.0.1 on 2026-01-08 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2, message='Le nom doit etre superieur a deux caracter')])),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
    ]
